### ISSUE TITLE
Don't preload ApplicationController

### ISSUE THREAD

**Issue by smtlaissezfaire** [sporkrb/spork#11]
ApplicationController is preloaded by spork by this file:

http://gist.github.com/165271

Unfortunately, my ApplicationController doesn't descend directly from ActionController::Base

http://gist.github.com/165273
http://gist.github.com/165274

This is causing a superclass mismatch when I load spork + try to run specs:

http://gist.github.com/39871732f9a02cf84bcc.

I'm not sure what the idea fix here is - Do we remove the stub (and cause ApplicationController to be loaded automatically in the prefork block), or do we parse application.rb, and load up any other descendent classes?

A middle ground might be this: if your application descends directly from ActionController::Base, preload the stub, otherwise, load the real file.

**Comment by timcharper** [comment]
Would it be out of the question to rework your inheritance scheme so that ApplicationController does inherit straight from "ActionController::Base" ?

IE:

class ApplicationController < ApplicationController::Base
end

class BaseApplicationController < ApplicationController
end

class UsersController < BaseApplicationController
end

In other words, what is specific motivation for ApplicationController not inheriting from ApplicationController::Base?

Loading the real file is problematic because it will start to grab and preload all sorts of dependencies from your app, causing you to have to restart Spork more often in order for it to see your changes. (additionally, it's not feasible to NOT preload ApplicationController, because rspec-rails WILL, along with all of your ApplicationController's dependencies).

**Comment by timcharper** [comment]
If the above isn't feasible, one possible option would be to create an over-ridable configuration parameter on Spork specifying where the preloadable-bare-bones ApplicationController lies, causing Spork to direct any attempt to load ApplicatonController there rather than it's own stubbish ApplicationController.

**Comment by smtlaissezfaire** [comment]
+1. 

Maybe I'm the only one in the world doing this, but I consider this a bug in spork.

Certainly, though, the inheritance scheme could use a module instead of a class.

**Comment by timcharper** [comment]
Taking the premise that this is a bug with Spork, how would you propose to fix it?

**Comment by smtlaissezfaire** [comment]
Not sure - this is why I was asking your advice ;)

As far as I'm concerned, if it _isn't_ a bug in Spork, it's (one of many) gross aspects of rails.

I'm up for moving my code into a module.

**Comment by timcharper** [comment]
I was trying to understand how you arrived at the conclusion that this is a bug in sport.

I would lean towards this being that rails wasn't intended to be used the way spork is using it, so spork has to do some forceful operations to get it to behave.  As such, a case could be made that rails has an underlying design flaw.

**Comment by smtlaissezfaire** [comment]
I originally called it a bug in spork because an older version of spork worked fine (that one was preloading ApplicationController, which I consider a nuisance more than anything else).

This version of spork won't work at all unless I first factor my code.

**Comment by smtlaissezfaire** [comment]
BTW: What are you imagining for the parameter idea?  Something like this:

http://gist.github.com/799ff78d064b48d2cf30 

?

**Comment by smtlaissezfaire** [comment]
Here's a patch:

http://github.com/smtlaissezfaire/spork/tree/application_controller_loading

**Comment by timcharper** [comment]
I believe that won't work because some parts of the rails code base (and rspec-rails too, I believe) explicitly call "require 'application_controller.rb'".  The way spork blocks this is by sticking the path with the blank application_controllers to the front of the lib path, satisfying all attempts to "require 'application_controller.rb'", and then later deliberately requiring the application's ApplicationController before the specs are run.

Tim

**Comment by smtlaissezfaire** [comment]
Yes - I realized that - which is why I didn't remove the application_helper.rb files, etc.

Sorry if that wasn't obvious from the specs

**Comment by timcharper** [comment]
closing
