### ISSUE TITLE
Extend RSpec Feature

### ISSUE THREAD

**Issue by jherdman** [sporkrb/spork#19]
One of the things I've found very confusing as I've begun to use Spork is knowing where to put my Spec::Runner code. It'd be nice if the feature file for RSpec showed a more complete example file. As it stands things are pretty skimpy.

**Comment by timcharper** [comment]
This is a great point. I will add a section to the wiki where people can link to their example spec_helper.rb files. Or, post them, whatever :-)

As it stands, things are pretty skimpy, but that's the point. It shows the minimum needed to get it working. I was under the assumption that that would be a better way to teach somebody how to use the tool, rather than showing a big complicated config file that may not apply to their specific use case.

But, I understand, it's always helpful to see different ways is being used.

**Comment by jherdman** [comment]
You're probably right that it's the best way to deal with things in the long run. I found that, for myself, it was trickiest figuring out where to put the Spec::Runner block. After that, if you're paying attention to documentation and examples, things are pretty clear.
