### ISSUE TITLE
support for Test::Unit

### ISSUE THREAD

**Issue by timcharper** [sporkrb/spork#5]
Lots of people still use it.  Vote for this if you'd like to see Test::Unit support for Spork.

**Comment by croaky** [comment]
Jason Morrison of thoughtbot has been looking into options for making our dozen or so large Test::Unit/Shoulda test suites faster.

I know he's looked at parallel_spec & testjour and made good progress on "parallel_test":

http://github.com/jasonm/parallel_test

Might be something there you can lift?

**Comment by rdp** [comment]
+1--without it my tests feel useless :)

**Comment by timcharper** [comment]
Hahahah, the +1 comments will never die no matter how many voting features you add to an issue tracker.

Thanks for the input.

**Comment by rdp** [comment]
And I would note that my comment was AFTER I had clicked the up arrow :)

Anyway turns out that snailgun appears to work with the Test::Unit style tests [just as an FYI if anybody wants to use something like spork now].
gem install snailgun autotest-rails

rails_app_home $ snailgun

rails_app_home $ fautotest

Looking forward to the same functionality in spork as well.
-r

**Comment by timcharper** [comment]
OK! It's been added... it's very rudimentary, but it works. Please play with it and let me know how it works:

sudo gem install spork-testunit

You'll need to upgrade to spork 0.6.0 in order for it to work.

**Comment by timcharper** [comment]
(more info at http://github.com/timcharper/spork-testunit/)

**Comment by timcharper** [comment]
marking closed here :) please leave further issues on spork-testunit's issue page:

http://github.com/timcharper/spork-testunit/issues
